In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns


In [2]:
# unpickle trips.pkl
trips = pd.read_pickle('trips_road_piece_msmsa.pkl')
print(len(trips))

3387


In [32]:
%matplotlib qt
# trip = trips[3000]

for trip in trips[3000:]:
    if len(trip[1]) < 500:
        continue
    trip_id = trip[0]
    trip_X = trip[1]
    trip_y = trip[2]
    trip_y_pred = trip[3]

    # convert trip_X to dataframe
    df = pd.DataFrame(trip_X, columns=['AbsoluteTime','Latitude', 'Longitude','Tsurf', 'Ta','Hours','Speed'])

   # convert trip_X to dataframe
    # df = pd.DataFrame(trip_X, columns=['Latitude', 'Longitude'])
    df['AbsoluteTime'] = df['AbsoluteTime'] - df['AbsoluteTime'].min()
    df['friction'] = trip_y
    df['friction_pred'] = trip_y_pred

    plt.close('all')

    # create subplots
    fig, ax = plt.subplots(1, 3, figsize=(15, 5))
    
    # # scatter plot of friction in a lat long 2D space
    # sns.scatterplot(x='Longitude', y='Latitude', data=df, hue='friction', ax=ax[0], s=10, palette='Spectral', hue_norm=(0.1,.9),legend=False)
    # ax[0].set_title('Measured - '+str(trip_id))

    # # scatter plot of friction in a lat long 2D space
    # sns.scatterplot(x='Longitude', y='Latitude', data=df, hue='friction_pred', ax=ax[1], s=10, palette='Spectral', hue_norm=(0.1,.9), legend=False)
    # ax[1].set_title('Predicted - '+str(trip_id))

    # scatter plot of friction in a lat long 2D space using plt
    sc = ax[0].scatter(df['Longitude'], df['Latitude'], c=df['friction'], cmap='viridis', s=5, alpha=0.5, vmin=.1, vmax=.9)
    ax[0].set_title('Measured - trip_id:'+str(trip_id))
    # scatter plot of friction in a lat long 2D space using plt
    sc = ax[1].scatter(df['Longitude'], df['Latitude'], c=df['friction_pred'], cmap='viridis', s=5, alpha=0.5, vmin=.1, vmax=.9)
    ax[1].set_title('Predicted')

    ax[0].set_xlim(23.1, 24.10)
    ax[0].set_ylim(60.30, 60.45)

    ax[1].set_xlim(23.1, 24.10)
    ax[1].set_ylim(60.30, 60.45)

    # add colorbar to the scatter plot
    fig.colorbar(sc, ax=ax[0], label='Friction')
    fig.colorbar(sc, ax=ax[1], label='Friction')

    
    # # Add a colorbar to the plot with the information from the scatter plot
    # norm = plt.Normalize(.1, .9)
    # sm = plt.cm.ScalarMappable(cmap="Spectral", norm=norm)
    # sm.set_array([])
    # # Add the colorbar to the figure
    # fig.colorbar(sm, ax=ax[0], label='Hue Value')
    # fig.colorbar(sm, ax=ax[1], label='Hue Value')

    # # line plot of friction over time
    # sns.lineplot(x='AbsoluteTime', y='friction', data=df, ax=ax[2], label='Measured')
    # ax[2].set_title('Measured vs. Predicted - '+str(trip_id) + ' - ' + str(trip[1][0,0]))
    # # line plot of friction over time
    # sns.lineplot(x='AbsoluteTime', y='friction_pred', data=df, ax=ax[2], label='Predicted')

    # plot friction over time using plt
    ax[2].plot(df['AbsoluteTime']/60, df['friction'], label='Measured')
    ax[2].plot(df['AbsoluteTime']/60, df['friction_pred'], label='Predicted')
    ax[2].set_title('Measured vs. Predicted - '+str(trip_id) + ' - ' + str(trip[1][0,0]))
    ax[2].legend()
    ax[2].set_xlabel('Time (min)')
    ax[2].set_ylabel('Friction')



    # make ylim .2 to 08
    ax[2].set_ylim(0, 1)

    fig.tight_layout()
    # plt.show()
    # if key n is pressed, go to next trip
    plt.pause(0.01)
    if plt.waitforbuttonpress():            
        continue


KeyboardInterrupt: 

[10139,
 array([[ 3.0528823e+07,  6.0382325e+01,  2.3200347e+01, ...,
         -1.0800000e+01,  8.0000000e+00,  7.8300000e+01],
        [ 3.0528824e+07,  6.0382231e+01,  2.3201517e+01, ...,
         -1.0800000e+01,  8.0000000e+00,  7.8200000e+01],
        [ 3.0528825e+07,  6.0382194e+01,  2.3201908e+01, ...,
         -1.0800000e+01,  8.0000000e+00,  7.8700000e+01],
        ...,
        [ 3.0530838e+07,  6.0312779e+01,  2.3998896e+01, ...,
         -1.0600000e+01,  8.0000000e+00,  9.9900000e+01],
        [ 3.0530839e+07,  6.0312756e+01,  2.3999394e+01, ...,
         -1.0500000e+01,  8.0000000e+00,  9.9100000e+01],
        [ 3.0530840e+07,  6.0312730e+01,  2.3999888e+01, ...,
         -1.0500000e+01,  8.0000000e+00,  9.8400000e+01]]),
 array([[0.71],
        [0.71],
        [0.71],
        ...,
        [0.71],
        [0.71],
        [0.71]]),
 array([[0.73],
        [0.73],
        [0.73],
        ...,
        [0.78],
        [0.79],
        [0.79]])]

In [5]:
# calculate the MAE of friction and friction_pred for each trip in trips
errors = []
for trip in trips[1:]:
    trip_id = np.array(trip[0]).squeeze()
    trip_X = np.array(trip[1]).squeeze()
    trip_y = np.array(trip[2]).squeeze()
    trip_y_pred = np.array(trip[3]).squeeze()
    # print(trip_y.shape, trip_y_pred.shape)
    errors.append(np.mean(np.abs(trip_y - trip_y_pred)))

print(np.mean(errors))

0.055067994635621134


In [74]:
# print number of records in all the trips
print(np.sum([len(trip[1]) for trip in trips]))

print(len(trips))


3403012
4404
